spring:
  profiles:
    include: API-KEY
  datasource:
    url: jdbc:mysql://localhost:3306/datajpa
    username: ${MYSQL_ID}
    password: ${MYSQL_PW}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace