spring:
  profiles:
    include: API-KEY
  datasource:
    url: jdbc:mysql://localhost:3306/jpashop
    username: ${MYSQL_ID}
    password: ${MYSQL_PW}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
  database: sql_server

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
